name: Release

on:
  release:
    types: [created]

jobs:
  homebrew:
    runs-on: macos-latest
    needs:
      - release
    steps:
      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.BREW_TOKEN }}
          formula: sniffer
          tag: ${{ github.ref }}
          revision: ${{ github.sha }}
